exports.API_KEY = process.env.API_KEY
exports.MONGODB_URI = process.env.MONGODB_URI
exports.SK_CRYPTOJS = process.env.SK_CRYPTOJS
exports.SK_TOKEN_JWT = process.env.SK_TOKEN_JWT
// FIREBASE
exports.FIREBASE_PUSH_KEY = process.env.FIREBASE_PUSH_KEY
// SENDGRID
exports.SENDGRID_API_KEY = process.env.SENDGRID_API_KEY
exports.SENDGRID_TEMPLATE_CONFIRM_MAIL_ID = process.env.SENDGRID_TEMPLATE_CONFIRM_MAIL_ID
exports.SENDGRID_TEMPLATE_RESET_PASSWORD_ID = process.env.SENDGRID_TEMPLATE_RESET_PASSWORD_ID
// AWS
exports.SECRET_ACCESS_KEY = process.env.SECRET_ACCESS_KEY
exports.ACCESS_KEY_ID = process.env.ACCESS_KEY_ID
exports.REGION = process.env.REGION
// NOTIFICATIONS
exports.SONG_NOTIF_DEFAULT = process.env.SONG_NOTIF_DEFAULT
// CONFIG APP
exports.MIN_ANDROID_VERSION = 1
exports.MIN_IOS_VERSION = 0
